### ISSUE TITLE
Poor performance when changing colors of spots in a plot, without changing positions

### ISSUE THREAD

**Issue by LucaMarconato** [pyqtgraph/pyqtgraph#1020]
### Short description

I have a scatterplot with 2000 points and I have a QSlider which changes the colors of the points, without changing their positions. I am experiencing poor performance and the feeling of the application is laggy. In the past I used a QSlider to change an image and the rendering time was almost 20 times faster, so I believe that the performance can be improved.

### Code to reproduce

I created a [minimal working example](https://github.com/LucaMarconato/dynamic_scatter_plot) which shows my problem and prints some benchmarks in the console.

### Expected behavior

The rendering time should be much smaller. Maybe achieving a short running time is more difficult in the general case in which also the positions of the points change, but in this case I want to replace only the colors.

### Real behavior

The rendering is slow.

### Tested environment(s)

 * PyQtGraph version: `0.10.0` 
 * Qt Python binding: `'PyQt5 5.9.2 Qt 5.9.6` 
 * Python version: `3.7.4`
 * NumPy version: `1.16.4` 
 * Operating system: macOS `10.14.6`
 * Installation method: `conda`

**Comment by 2xB** [comment]
For those who want to look into this: `pg.graphicsItems.ScatterPlotItem.SymbolAtlas` is the class that takes the most time here. It is only a bit longer than 100 lines, so if one takes some time, one can understand and optimize it.

**Comment by 2xB** [comment]
Note that in case of this specific class, a rewrite might even be a good idea, as it could also improve readability.

**Comment by 2xB** [comment]
Also note that the calculation of `arr` in `buildAtlas` could make heavy use of pre-caching for each symbol and size.

**Comment by wailashi** [comment]
I'm dealing with the same problem currently. I managed to improve performance by pre-calculating a palette of QBrushes and then using `setBrush()` on each SpotItem in the scatter plot. For my plot that means updating 2800 points takes about 0.08 seconds or around 12 FPS.

@LucaMarconato maybe you could change your example to have an FPS counter and continuously update the colours at random. Your code could then be used as a benchmark.

**Comment by janto** [comment]
I am interested in speeding up the use case where both the colors and size changes. So I'm wondering if it is viable for the atlas to be used when pxMode=False? Zooming in and out seems to happen at discrete steps in my application (mousewheel steps), so it wouldn't be an infinite amount that needs caching. 

Looking at the code I see that `key = id(symbol), size, id(pen), id(brush)` is used together with a weakref dictionary. I've only just started to look at the code, but this doesn't seem right for two reasons. One is that the weakref will almost instantly be forgotten because that tuple doesn't exist anywhere else. The other is that the use of id() on brush might always be unique because brush goes through mkBrush which creates a copy.

Again, I could be completely wrong since I'm just getting into the code. I see there was a TODO in the code (no longer) that mentioned string keys would be better. How would that have worked?

**Comment by 2xB** [comment]
The last contributions to `SymbolAtlas` were done by @termim and - quite recently - @danielhrisca. Maybe one of them has insights?

**Comment by danielhrisca** [comment]
@LucaMarconato can you try with the latest develop code to see if it is better?

> I see there was a TODO in the code (no longer) that mentioned string keys would be better. How would that have worked?
It would have just been used as a human readable way to access the np.recarray fields. This is in fact slower than index access

**Comment by danielhrisca** [comment]
Hello all,

I've made a new PR that improves the execution time a bit #1198 

One aspect that could be improved is the case were the initial spots are computed when a ScatterPlotItem is first created. In this case we only need to create a QRectF and populate the 'sourceRect' field with it in the updateSpots method

**Comment by LucaMarconato** [comment]
Hi @danielhrisca, thank you a lot for your contribution. I have just tested your code [on this example](https://github.com/LucaMarconato/dynamic_scatter_plot). With your code points are not being drawn on my machine (latest macOS), while with the latest pyqtgraph I see them. So I can't tell if I see a performance enhancement. Maybe you can also use the code I linked to compare the performance between versions.
Anyway, despite seeing just the black background and not the points, I see that the slider is still lagging behind the mouse, so probably there is still room for improvements. 
Are you using openGL for rendering the points? I think that would dramatically improve the performance.

**Comment by danielhrisca** [comment]
For some reason the point colors are all set to black.

**Comment by lidstrom83** [comment]
I created a PR to cache the `QBrush` objects in your example. Then I think #1420 should resolve your issue.

**Comment by j9ac9k** [comment]
Fixed with #1420

**Comment by LucaMarconato** [comment]
@lidstrom83 @j9ac9k I have tried again the example code that I have linked above with the latest PyQtGraph and I still see poor performance. I guess that at this point maybe there is something wrong in my code. Can you please upload the code that you use to check that the issue was resolved? Thank you

**Comment by j9ac9k** [comment]
Hi @LucaMarconato You're not the first person to report poor performance (still) on the master branch, I believe you, but there is a test case we haven't been able to benchmark.  @lidstrom83 developed https://github.com/pyqtgraph/pyqtgraph/blob/master/examples/ScatterPlotSpeedTest.py which lets you toggle through a bunch of options and get the relative FPS.  This is the tool we used to measure significant performance improvements virtually across the board.  

While not in a very obvious place, @lidstrom83 also put commented notes in ScatterPlotItem regarding performance notes:

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ScatterPlotItem.py#L25-L36

Things you can do in your code, without seeing it, is 

1. Reuse QPen and QBrush objects as much as possible instead of re-creating them.
2. Use cacheMode if possible

If you can come up with some kind of usage of ScatterPlotItem that is slower now than it was with 11.0, I'd _love_ to see it, so I can use `git bisect` to identify what change in the code-base induced any slow downs your experiencing.  Right now, the biggest performance hit that ScatterPlotItem.py has taken since 0.11.0 was making the background of GraphicsWidgets transparent.  I've since changed that (but it's not in any current release, it will be in the next release).
