### ISSUE TITLE
Zooming out can violate lockAspect option of viewBox

### ISSUE THREAD

**Issue by ibrewster** [pyqtgraph/pyqtgraph#1030]
### Short description
When zooming out on a plot with x and y limits, the lockAspect option can be violated at extreme zoom levels.

### Code to reproduce

```python
import pyqtgraph as pg

test_view_box = pg.ViewBox(lockAspect=1)
test_view_box.setLimits(**{
            'xMin': -10,
            'xMax': 10,
            'yMax': 10,
            'yMin': -10,
})
        
test_plot_widget = pg.PlotWidget(viewBox=test_view_box)
test_plot_widget.show()
```

### Expected behavior
When zooming out, zoom should stop once EITHER the x or y limits are reached, such that the aspect ratio specified in lockAspect is maintained. That is, with the above example, if the widget is displayed taller than it is wide, when zooming out once the Y axis reaches its limits of -10 to 10, additional zooming out should be disabled, even though the x axis is only part way to limit. The user should still be able to pan left and right since X is not at limits, but not zoom out more, since that would violate either the y limits or the aspect ratio (aspect ratio, in this case).

### Real behavior
Zoom out continues until BOTH the x and y limits are reached, violating the set aspect ratio if necessary to fit both limits in the window/widget. Only if the widget size exactly matches the set aspect ratio will you get no distortion.

For example, with the code above, imagine the situation where the window (widget) is displayed twice as tall as it is wide. While zoomed in to relatively small values, everything is fine and lockAspect works. If the range of 2 units on the Y axis, you get a range of 1 unit on the X axis as expected. When zooming out on this view, once the Y axis reaches it's zoom limit (with a range of -10 to 10), you can still zoom out more - except only the X axis changes, thereby violating the lockAspect.

### Tested environment(s)

 * PyQtGraph version: 0.11.0.dev0+g229f650
 * Qt Python binding: PySide2 5.12.3 Qt 5.12.3
 * Python version: 3.7.2
 * Operating system: Mac OS X Mojave
 * Installation method: pip

### Additional context
I'm using this to display a map image. Ideally, the user could zoom "all the way" out without the map getting distorted or the view box extending past the extents of the map. At the moment, at zoom levels close to minimum, the map starts distorting in order to fit in the full x and y limits.

**Comment by 2xB** [comment]
For anyone who wants to give this a try for a Pull Request, from brief looking the following is to do:

Currently, the ViewBox range can be set to values that are outside the specified region, but when painted, `ViewBox.updateViewRange(...)` calculates a ViewBox that matches the specified region. One can see that by scrolling out further when the limits are reached, and then scrolling back: One did not see it, but still scrolled beyond the specified limit, so scrolling back takes surprisingly long.

What had to be done is moving this logic to `ViewBox.setRange(...)`, so it is not possible to scroll over the limit in the first place so that later no correction has to be applied. Then this logic has to be reworked to take the aspect ratio into account.

The relevant lines in `ViewBox.updateViewRange` start with 
```
# ----------- Make corrections for view limits -----------
```
.

**Comment by ibrewster** [comment]
I have fixed this issue in my development fork, and could certainly create a pull request, but I'm a bit hesitant to due to the fact that I have only tested the changes in my application - there could easily be situations that the logic I used doesn't handle properly. Is this an issue for creating the request?

**Comment by j9ac9k** [comment]
We would welcome a PR, but it should have some test code bundled with it.  When looking at the PR we may add more test cases and see if we can address them there.

**Comment by goodboy** [comment]
I believe I am possibly having this issue which I hacked here:
https://github.com/pikers/piker/commit/c073c50f15e897d137d5415fc31dfc8c5139a45b

It's still not working in the maximum "zoomed out" case (pans left after hitting the max datums on screen case).

In order to do this I have to override the `ViewBox.wheelEvent()` which turned out to be tricky since `PlotItem` has no easy way to pass in a `ViewBox` subtype. I made some changes on that end that I'll bring up I guess.

The other thing is being able to configure the zoom "center" point.
For my case I wanted it to be the right y-axis side of the plot that is held fixed but there is no easy was to accomplish this without the method override. I wonder if a small method to accomplish this would be handy?
