### ISSUE TITLE
Adding TextItem to plot changes the axis range (appears on Ver. 0.11, the bug was not present on 0.10)

### ISSUE THREAD

**Issue by 3fon3fonov** [pyqtgraph/pyqtgraph#1373]
Now that I am migrating to Version 0.11, I have noticed an annoying problem that was not present on 0.10.

When I add ArrowItem and TextItem to an existing plot, I get this:

![Ticks_wrong](https://user-images.githubusercontent.com/44244057/93709887-6474a200-fb42-11ea-84fe-a27563fa9581.png)

Whereas I would expect this (pyqtgraph ver. 0.10):

![Ticks_right](https://user-images.githubusercontent.com/44244057/93709898-77877200-fb42-11ea-9c90-0f4aff56483a.png)

I noticed that this happens only if I label the peaks by calling:

```
    def label_peaks(self, plot_wg2, pos_peaks, GLS = True, o_c = False, activity = False, MLP = False, DFT=False):

        if GLS == True and DFT == False and self.avoid_GLS_RV_alias.isChecked():
            x_peaks = pos_peaks[0][pos_peaks[0]>1.2]
            y_peaks = pos_peaks[1][pos_peaks[0]>1.2]
        else:
            x_peaks = pos_peaks[0]
            y_peaks = pos_peaks[1]


        if GLS == True:
            N_peaks = int(self.N_GLS_peak_to_point.value())
            if o_c == True:
                log = self.radioButton_RV_o_c_GLS_period.isChecked()
            elif activity == True:
                log = self.radioButton_act_GLS_period.isChecked()
            elif MLP == True:
                log = self.radioButton_RV_MLP_period.isChecked()
                N_peaks = int(self.N_MLP_peak_to_point.value())
            elif DFT == True:
                log = self.radioButton_RV_WF_period.isChecked()
                N_peaks = int(self.N_window_peak_to_point.value())

            else:
                log = self.radioButton_RV_GLS_period.isChecked()

            type_per = "GLS"
        else:
            N_peaks = int(self.N_TLS_peak_to_point.value())
            log = False
            type_per = "TLS"

        if len(x_peaks) <  N_peaks:
            N_peaks = len(x_peaks)
            print("You have reached the maximum number of %s peaks."%type_per)

        for i in range(N_peaks):

            text_arrow = pg.TextItem("", anchor=(0.5,1.9))

            if log == True:
                arrow = pg.ArrowItem(pos=(np.log10(x_peaks[i]), y_peaks[i]), angle=270)
                text_arrow.setText('%0.2f d' % (x_peaks[i]))
                text_arrow.setPos(np.log10(x_peaks[i]),y_peaks[i])
                
            elif log == False and GLS == True:   
                arrow = pg.ArrowItem(pos=(1/x_peaks[i], y_peaks[i]), angle=270)
                text_arrow.setText('%0.2f d' % (x_peaks[i]))
                text_arrow.setPos(1/x_peaks[i],y_peaks[i])
                
            elif log == False and GLS == False: 
                arrow = pg.ArrowItem(pos=(x_peaks[i], y_peaks[i]), angle=270)
                text_arrow.setText('%0.2f d' % (x_peaks[i]))
                text_arrow.setPos(x_peaks[i],y_peaks[i])


            plot_wg2.addItem(arrow)
            plot_wg2.addItem(text_arrow) 

```

The "bug" appears only if I use TextItem. Adding ArrowItem behaves OK.
So what changed w.r.t. version 0.10?

**Comment by ixjlyons** [comment]
Hmm, I took a stab at replicating the issue but haven't been able to so far. What I've tried:

```python
import pyqtgraph as pg

app = pg.mkQApp()

pw = pg.plot([10, 100, 1000, 100000], [0.1, 0.8, 0.2, 0.4])
pw.plotItem.setLogMode(x=True)

arrow = pg.ArrowItem(pos=(2, 0.8), angle=270)
pw.addItem(arrow)

text = pg.TextItem("hey", anchor=(0.5, 2))
text.setPos(2, 0.8)
pw.addItem(text)

app.exec_()
```

It seems to work fine on 0.11.0 and current master.

> So what changed w.r.t. version 0.10?

Well, a ton of stuff actually. There was a long period of time between the releases and many accumulated changes that went into it. If you're able to help modify the code above to reproduce the issue (or cut down your own code to something runnable standalone), that'd be extremely helpful. Otherwise, you could git bisect to try to identify which commit introduced the issue. If you're interested and want help with doing so let me know.

It could be related to the context the `PlotItem` is in, it's hard to say.

Also, what Qt version and which Qt python bindings are you using?

**Comment by 3fon3fonov** [comment]
Hi @ixjlyons,

To make a working/failing minimal example from my code will take me some time..., The code is quite nested, but I will try as soon as I find time this week. 

Meanwhile, I had some success to plot the periodogram close to what I had before. I just added this to the end of the function above.


```
...
...
            plot_wg2.addItem(text_arrow, ignoreBounds=True)  
        plot_wg2.setRange(yRange=(-0.001, max(y_peaks)+0.3*max(y_peaks)), padding=0.01)
```

This leads to the following view:

![Ticks_right2](https://user-images.githubusercontent.com/44244057/93723435-db3f8880-fb9e-11ea-8665-a00f0545a798.png)


However, pressing the "autoRange" button on the left of the scene leads to this:

![Ticks_wrong2](https://user-images.githubusercontent.com/44244057/93723453-ee525880-fb9e-11ea-867b-5dba732bb8a9.png)

This is also true for your minimal example:

![test](https://user-images.githubusercontent.com/44244057/93723466-0629dc80-fb9f-11ea-8fa1-91094c22e2d7.png)

As you can see, it hides the label. You can try to reproduce it, if you zoom-in, move the scene, etc and then press  "autoRange".

This was definitely not the case with 0.10. It must be something with the bounds/anchor of the TextItem.

**Comment by 3fon3fonov** [comment]
Ok, so I found some time to strip 99.99% of my code to make a minimal example! In the zip file you will find:

* gls_data.csv --> the data time series exported as a .csv file. (BTW, when the x-axis is logarithmic,  pyqtgraph exports the exponent, not the actual period that is displayed! I find this problematic, especially in this case, and when such a plot is exported to matplotlib)

* gls.ui --> designer .ui file
* gls.py  --> .ui translated to .py
* gls_test.py  --> run this file.

I tried to make it as close as possible to my setup. And... the bug is there:
![gls_test](https://user-images.githubusercontent.com/44244057/94057850-7d01e800-fde0-11ea-9c1b-2f4a61f0e541.png)
[gls_plot_example.zip](https://github.com/pyqtgraph/pyqtgraph/files/5270560/gls_plot_example.zip)


I have some success if I add: 
`
plot_wg2.addItem(text_arrow, ignoreBounds=True) `

![gls_test2](https://user-images.githubusercontent.com/44244057/94058162-fa2d5d00-fde0-11ea-8a71-ca03a8862643.png)


but is still not good enough and after "auroRange" the label is hidden again. Also, it is not stable... after zoom and then "autoRange" the scene is always different.

**Comment by 3fon3fonov** [comment]
Any ideas on how to solve this issue?

**Comment by j9ac9k** [comment]
Hi @3fon3fonov,

Sorry it's taking us a while to follow up.  We're been working on merging the existing PRs.

As you have code to replicate, if you're comfortable, I would suggest giving `git bisect` a go, and see if you can identify the commit that took place that causes the change in behavior.

Normally we would handle this, but as we still have 40 outstanding PRs; it may be a while before we start tackling issues.

If you'd like some help with `git bisect` let me know and I can talk you through it a bit more.

**Comment by 3fon3fonov** [comment]
I have no idea how to use `git bisect `I am also swarmed with work, but I will be happy to help though...  just let me know what do you expect from me and I will try to get it done soon.

**Comment by j9ac9k** [comment]
don't worry about it if you're not comfortable w/ `git bisect`; in case you're unaware, git-bisect should identify the commit where the behavior changed, that's often very helpful to try and isolate what's causing the behavior we don't want...

**Comment by pijyoi** [comment]
git bisect points to d77ad273c71870881c3fda3d2b49d3488f100425

**Comment by j9ac9k** [comment]
Thanks for identifying the commit @pijyoi 

Good news, the diff is small, bad news, it's in `ViewBox.py`.  I'll try and poke around a bit more later tonight.   @3fon3fonov thanks for providing the small code example, as this will make it easier to test potential fixes.

**Comment by j9ac9k** [comment]
Hmm...problem seems to be with the implementation of the `ViewBox.update` method (and the removal of the `ViewBox.checkSceneChange`)

**Comment by j9ac9k** [comment]
Ok, got it to "work", but indication appears to be that `ViewBox._autoRangeNeedsUpdate` is not being updated properly in this case... so even though I got it to work, not ready to implement a fix.

Most minimal changes I've made so far are:

- Change the order of the calls in `ViewBox.update()`
    ```python
        def update(self, *args, **kwargs):
            GraphicsWidget.update(self, *args, **kwargs)
            self.prepareForPaint()
    ```
- Get rid of the if-check in `ViewBox.prepareForPaint()`
    ```python
        def prepareForPaint(self):
            #autoRangeEnabled = (self.state['autoRange'][0] is not False) or (self.state['autoRange'][1] is not False)
            # don't check whether auto range is enabled here--only check when setting dirty flag.
            # if self._autoRangeNeedsUpdate: # and autoRangeEnabled:
            self.updateAutoRange()
            self.updateMatrix()
    ```
- Add a call to `ViewBox.update()` in `ViewBox.paint()`
    ```python
        def paint(self, p, opt, widget):
            self.update()
            if self.border is not None:
                bounds = self.shape()
                p.setPen(self.border)
                #p.fillRect(bounds, QtGui.QColor(0, 0, 0))
                p.drawPath(bounds)
    ```

**Comment by j9ac9k** [comment]
ok... I'm starting to think this isn't a pyqtgraph bug:

I've been working working on a simplified version of the code, and it's running fine:

```python
import pyqtgraph as pg
from pyqtgraph.Qt import QtCore, QtGui
import numpy as np
from scipy.signal import argrelextrema 


def identify_power_peaks(x,y,sig_level=np.array([]), power_level=np.array([]) ):

    per_ind = argrelextrema(y, np.greater)
    per_x   = x[per_ind]
    per_y   = y[per_ind]

    peaks_sort = sorted(range(len(per_y)), key=lambda k: per_y[k], reverse=True)

    per_x   = per_x[peaks_sort]   
    per_y   = per_y[peaks_sort]

    peaks_pos = [per_x,per_y]
    return text_peaks , peaks_pos

def label_peaks(plot_wg2, pos_peaks, GLS = True, o_c = False, activity = False, MLP = False, DFT=False):
    if GLS == True and DFT == False:
        x_peaks = pos_peaks[0][pos_peaks[0]>1.2]
        y_peaks = pos_peaks[1][pos_peaks[0]>1.2]
    else:
        x_peaks = pos_peaks[0]
        y_peaks = pos_peaks[1]

    if GLS:
        N_peaks = 4
        if o_c:
            log = True

        else:
            log = True

        type_per = "GLS"
    else:
        N_peaks = 4
        log = False
        type_per = "TLS"

    if len(x_peaks) <  N_peaks:
        N_peaks = len(x_peaks)
        print("You have reached the maximum number of %s peaks."%type_per)

    for i in range(N_peaks):
        text_arrow = pg.TextItem("", anchor=(0.5,1.9))
        if log:
            arrow = pg.ArrowItem(pos=(np.log10(x_peaks[i]), y_peaks[i]), angle=270)
            text_arrow.setText('%0.2f d' % (x_peaks[i]))
            text_arrow.setPos(np.log10(x_peaks[i]),y_peaks[i])
        elif not log and GLS:   
            arrow = pg.ArrowItem(pos=(1/x_peaks[i], y_peaks[i]), angle=270)
            text_arrow.setText('%0.2f d' % (x_peaks[i]))
            text_arrow.setPos(1/x_peaks[i],y_peaks[i])
        elif not log and not GLS: 
            arrow = pg.ArrowItem(pos=(x_peaks[i], y_peaks[i]), angle=270)
            text_arrow.setText('%0.2f d' % (x_peaks[i]))
            text_arrow.setPos(x_peaks[i],y_peaks[i])
        else:
            continue
        plot_wg2.addItem(arrow)#, ignoreBounds=True)   
        plot_wg2.addItem(text_arrow) #, ignoreBounds=True)  
    return

app = pg.mkQApp()
mw = QtGui.QMainWindow()
cw = QtGui.QWidget()
mw.setCentralWidget(cw)

l = QtGui.QVBoxLayout()
cw.setLayout(l)
pw = pg.PlotWidget(name="Plot1")
l.addWidget(pw)

mw.show()


power_levels = np.array([0.1, 0.01, 0.001])
model_width = 1

file_ = "gls_data.csv"

period        =  np.genfromtxt("./%s"%(file_),skip_header=1, unpack=True, skip_footer=0, delimiter=",", usecols = [0]) 
power         =  np.genfromtxt("./%s"%(file_),skip_header=1, unpack=True, skip_footer=0, delimiter=",", usecols = [1]) 

period = 10**period


pw.setLogMode(True, False)
pw.plot(period, power, pen={'color': 'r', 'width': model_width},symbol=None)
pw.setLabel('bottom', 'frequency [1/d]', units='',  **{'font-size':'9pt'}) 

text_peaks, pos_peaks = identify_power_peaks(period, power, power_level = power_levels )

label_peaks(pw, pos_peaks, GLS=True, o_c=False)

## Start Qt event loop unless running in interactive mode or using pyside.
if __name__ == '__main__':
    import sys
    if (sys.flags.interactive != 1) or not hasattr(QtCore, 'PYQT_VERSION'):
        QtGui.QApplication.instance().exec_()
```

I'll keep adding more to this and I'll see if it can be identified where things break...

**Comment by j9ac9k** [comment]
@3fon3fonov ok I figured out your bug, it's that you call `window.show()` at the very end.  I can get intended behavior by calling `self.show()` in your main window `__init__` method:

```python
    def __init__(self):
        QtWidgets.QMainWindow.__init__(self)
        Ui_MainWindow.__init__(self) 
        self.setupUi(self)

        self.show()

        self.initialize_font_plot()
        self.initialize_plots()
        self.make_GLS_plots()   
```

I'm going to close out this issue in the meantime; this issue pointed out a lot of code I don't like in `ViewBox.py`...but that's for another time.

**Comment by j9ac9k** [comment]
I forgot to add, if you're still running into an issue, let us know; but the fact it worked before was likely a side-effect of `paint` being called multiple times over; and when we fixed that bug, doing proper scaling/positioning before `.show()` is called no longer worked.

**Comment by pijyoi** [comment]
I still see the problem of the Auto-Range button not giving consistent scaling results, as mentioned by @3fon3fonov before.
If the TextItem is not added, then the scaling is consistent.

I have a more minimal example below that exhibits this behavior:
```python
import pyqtgraph as pg
import numpy as np

def do_plot(pw):
    x = np.linspace(-3, 3, 1001)
    y = np.abs(np.sinc(x))
    pw.plot(x, y)
        
    inds = [np.argmax(y)]
    for ind in inds:
        xp, yp = x[ind], y[ind]

        text = pg.TextItem('{:.2f}'.format(xp), anchor=(0.5,1.9))
        text.setPos(xp, yp)
        arrow = pg.ArrowItem(pos=(xp, yp), angle=270)
            
        pw.addItem(arrow)
        pw.addItem(text)

def main():
    app = pg.mkQApp()
    pw = pg.PlotWidget()
    pw.resize(640,480)
    pw.show()
    do_plot(pw)
    app.exec_()

if __name__ == '__main__':
    main() 
```

![sinc_scale](https://user-images.githubusercontent.com/2657027/98525374-537b1e00-22b3-11eb-9abb-73e266420b38.PNG)

**Comment by j9ac9k** [comment]
Thanks for the minimum example @pijyoi I'll re-open the issue and take a look when I have some time.

**Comment by j9ac9k** [comment]
@pijyoi what version are you running?  This is what it looks like on the current master branch on macOS:

![image](https://user-images.githubusercontent.com/646398/98587800-82779c80-227f-11eb-8588-bfcae9598427.png)

**Comment by pijyoi** [comment]
Sorry if I was not clear enough. I get the same plot as you when the program is executed. 
The issue occurs when you zoom and click the auto-range button. Each zoom + auto-range click doesn't always yield back the same plot. 

I am using master branch.

**Comment by j9ac9k** [comment]
Hmm....that's odd, as the auto-scale button is working for me correctly
![autoscale](https://user-images.githubusercontent.com/646398/98608216-90d5b080-229f-11eb-9ae0-f3ced2422760.gif)

**Comment by j9ac9k** [comment]
Ahh I did break it when I zoomed _way_ out....

**Comment by pijyoi** [comment]
I re-ran git bisect on this minimal example since it might appear to be a different issue (bad plot after zoom-out plus click on auto-scale) from the original (immediate bad plot).
But yes, it is the same commit:  d77ad273c71870881c3fda3d2b49d3488f100425

**Comment by j9ac9k** [comment]
I think for this we are going to need to expand the test suite.  I get
uncomfortable messing with ViewBox.py code.

**Comment by j9ac9k** [comment]
So...I'm tracing the issue down to an effectively bogus return from  `ViewBox.mapFromItemToView`  which is called from `ViewBox.childrenBounds`


Since ViewBox.py is pretty unfriendly toward having `breakpoint()` inserted, I'm debugging via print statements... awesome

I inserted these print statements:

```python
            else:
                if int(item.flags() & item.ItemHasNoContents) > 0:
                    continue
                else:
                    bounds = item.boundingRect()
                    print(f"{bounds=}")
                bounds = self.mapFromItemToView(item, bounds).boundingRect()
                print(f"{bounds=}")
                itemBounds.append((bounds, True, True, 0))
```

When things are working right, this generates the following code

```
bounds=PyQt5.QtCore.QRectF(-17.0859375, -45.599999999999994, 34.171875, 24.0)
bounds=PyQt5.QtCore.QRectF(-0.18088898148753765, 1.0572888734733237, 0.3617779629750753, 0.06365430385924875)
bounds=PyQt5.QtCore.QRectF(-17.0859375, -45.599999999999994, 34.171875, 24.0)
bounds=PyQt5.QtCore.QRectF(-0.1807549921116422, 1.057895180624668, 0.3615099842232844, 0.06432797847185312)
```

...but when things go astray, it generates the following output:

```
bounds=PyQt5.QtCore.QRectF(-17.0859375, -45.599999999999994, 34.171875, 24.0)
bounds=PyQt5.QtCore.QRectF(-17.0859375, -44.599999999999994, 34.171875, 24.0)
bounds=PyQt5.QtCore.QRectF(-17.0859375, -45.599999999999994, 34.171875, 24.0)
bounds=PyQt5.QtCore.QRectF(-1.0897933060987466, 10421320140464.479, 2.179586612197493, 11579244600514.979)
```

In this case, the last line is what caught my eye, it says the boundingBox of the textItem is _quite_ large (in this case, in the y-axis).

Still not sure why I'm getting that bogus return....will keep investigating.

**Comment by j9ac9k** [comment]
So...at the very end of `ViewBox.updateMatrix()` there is the signal `sigTransformChanged`; if you comment out that signal being emitted, when you press the autoscale button, you get a brief frame of it being completely the wrong size (looks like way too zoomed in) and then a second redraw to the correct range.

I commented out the code in the slot that is connected to that signal; but the ranging is still not right...not sure what else that signal would be connected to that would cause this issue

**Comment by goodboy** [comment]
As per some brief discussion @j9ac9k and I had through chat, we might want to play with setting `force` back to `True` in [`TextItem.updateTransform()`](https://github.com/pyqtgraph/pyqtgraph/blob/46dafe4803ff29346416b400e204058edc6fdee5/pyqtgraph/graphicsItems/TextItem.py#L191) since the change in `19 may have exposed a caching logic bug here.

**Comment by j9ac9k** [comment]
Still no closer to figuring out where the bug is... but a little more context in case anyone else feels like tackling this.

This is the first sign of a problem from what I can tell:

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L909

This line is returning "bounds" that are not correct.

Diving into `ViewBox.childrenBounds` method, The first sign of an issue is here:

https://github.com/pyqtgraph/pyqtgraph/blob/master/pyqtgraph/graphicsItems/ViewBox/ViewBox.py#L1403

When I look into the `updateMatrix` function, I get some (nearly) ideal behavior when I comment out `self.sigTransformChanged.emit(self)` at the end of `ViewBox.updateMatrix`.  

Given that I cannot replicate this issue with just the ArrowItem, but I can replicate it with only the TextItem, I suspect the bug is somewhere in `pg.TextItem`'s  `updateTransform` method, but there isn't that much code there; so i'm not sure what there is being problematic... 

The reason this wasn't an issue before the old commit pre 0.11.0 was because before that commit, the ViewBox would conduct multiple paint calls (when only one was/should have been necessary)... anyway I'm going to put this issue away for a while because I'm not making any more headway on it.  

Any help/assistance would be appreciated here.  Thanks again @pijyoi for providing that minimal example, it's been helpful!

**Comment by j9ac9k** [comment]
I think I got things working by commenting out the first call to `self.updateMatrix()` in `ViewBox.resizeEvent` but I'm going to need to experiment a bit more before I suggest that as the appropriate fix...

**Comment by j9ac9k** [comment]
@pijyoi would you mind testing the version of pyqtgraph in PR #1435 ?  I _think_ that should do it, as I said before, `ViewBox.py` is _super_ fragile.

**Comment by pijyoi** [comment]
@j9ac9k , I checked out your PR #1435 
The auto-scale does not re-create the same plot as on program start.

at program start:
![Capture_start](https://user-images.githubusercontent.com/2657027/98904806-464d7180-24f5-11eb-8f4e-5e84fac084c7.PNG)

zoom:
![Capture_zoom](https://user-images.githubusercontent.com/2657027/98904841-536a6080-24f5-11eb-9c61-81c649c44d42.PNG)

after auto-scale:
![Capture_autoscale](https://user-images.githubusercontent.com/2657027/98904860-5b2a0500-24f5-11eb-816c-ea37766db323.PNG)

**Comment by j9ac9k** [comment]
Grr... I fired it up this morning, and now it's blowing up on me _routinely_ ....wonder if there is some race condition

**Comment by j9ac9k** [comment]
Ok, I think I got it working (hopefully?) ... Mind giving it another try?

I'm going to definitely want to add a test for this..but you know, have to get back to my paying job 😆

**Comment by pijyoi** [comment]
Yes, it seems to have fixed both my minimal example as well as @3fon3fonov original example. Zoom + auto-scale now consistently gets back to the starting plot.

**Comment by j9ac9k** [comment]
🎊 

thanks for testing .... it may be a bit before this gets merged as I'm going to want to get a test for this.

**Comment by j9ac9k** [comment]
well, crud... that one test won't pass unless I do not have that `self.prepareForPaint()` call int he paint method, ... but if I don't have it, the auto-sizing is clearly not right...I'll investigate the test a bit more

**Comment by 3fon3fonov** [comment]
Nice to know you are actively working on this guys! I am quite surprised this get so viral! As I can see, however, it is not a bug I could solve myself... Looking forward to seeing the fix implemented. Let me know if you need some assistance with testing, for example.

**Comment by j9ac9k** [comment]
This was pretty brutal to track down, the small working example to highlight the issue, in combination with git bisect is really what allowed for pointing the finger at the culprit.   At the end of the day, this issue highlights the complexity of the code in `ViewBox.py`; and I wish there was an easier solution to refactoring/testing more thoroughly.

Also I just realized that I didn't close this issue, so I'll close it now that #1435 fixes it.
