### ISSUE TITLE
no 'ScatterPlotSpeedTestTemplate_pyqt5' on PyQt5 on Windows

### ISSUE THREAD

**Issue by stonebig** [pyqtgraph/pyqtgraph#259]
testing on Windows Qt5.5.1/ PyQtgraph github of 20160102, I have the following error on the "Scatter Plot Update" test:

```
Using PyQt5 (default graphics system)
Using PyQt5 (default graphics system)
Traceback (most recent call last):
  File "D:\WinPython\basedir34\buildQt5\winpython-3.4.4.amd64\python-3.4.4.amd64
\lib\site-packages\pyqtgraph\examples\ScatterPlotSpeedTest.py", line 26, in <mod
ule>
    from ScatterPlotSpeedTestTemplate_pyqt5 import Ui_Form
ImportError: No module named 'ScatterPlotSpeedTestTemplate_pyqt5'

```

**Comment by campagnola** [comment]
Thanks! This should be fixed as of 0.10.0.

**Comment by deepSymmetry** [comment]
Not fixed. File present is ScatterPlotSpeedTestTemplate_pyqt.py. Renaming it did not help.

**Comment by LucaMarconato** [comment]
I think it is still not fixed

**Comment by j9ac9k** [comment]
Hi @LucaMarconato Sorry for the super-long awaited response.  With #1566 having been merged, we no longer use those template files; also the test is much more exhaustive of various combinations.  If you're still using the library, please give it a go!
