### ISSUE TITLE
PyQt5, Retina Display, OpenGL windows wrong size.

### ISSUE THREAD

**Issue by mshunshin** [pyqtgraph/pyqtgraph#422]
Using PyQtGraph 0.10 with PyQt4 and an OpenGL widget (either imageview or GLViewWidget) results in appropriately sized images and widgets; but, as with all Qt4 things a bit blurry.

I have just moved my codebase to Qt5. With this, all the widgets seem to work and are at 'retina' resolution, apart from the GL widgets, which are at 'retina' resolution, but a quater of the expected size.

To fix you need to sprinkle *self.devicePixelRatio(), in places were there is self.width() and self.height() on things relating to the GL view port to make them the correct size.

i.e.

(0, 0, self.width(), self.height()) becomes

(0, 0, self.width()*self.devicePixelRatio(), self.height()*self.devicePixelRatio())

There are three places: 

opengl/GLViewWidget.py
def projectionMatrix()
def getViewPort()

widgets/RawImageWidget.py
def paintGL()

devicePixelRatio is present in PyQt4 (according to the docs), but I haven't checked if these changes are backward compatible.

BW

Matt

**Comment by mshunshin** [comment]
It might not fix it on platforms that incorrectly report self.devicePixelRatio(); but so long as they report 1 it won't make it worse.
M

**Comment by ogorda** [comment]
That didn't work for me. I have modified the **opengl/GLViewWidget.py** and **widgets/RawImageWidget.py** with _*self.devicePixelRatio()_ as given above, but when I run the code I still get only a quarter of the OpenGL widget viewport drawn.
I am running Macbook Pro with Retina display, OS X El Capitan Version 10.11.6, PyQt5, Qt Creator 4.3.0 based on Qt 5.8.0. 
I am quit a newcomer with PyQt: maybe there is a trick to somehow "apply" the above changes in the code?

**Comment by mshunshin** [comment]
Difficult to say. Troubleshooting tips would be:
1) Make sure you are changing it in all three places
2) Make sure you have modified the version you are actually using - best to download pyqtgraph and stick the sub-folder of pyqtgraph in your project folder and import that.
3) Check that it is reporting the correct devicePixelRatio() - add a few print(self.devicePixelRatio()) next to the places you change.

**Comment by ogorda** [comment]
Dear Mattew, thanks for your advices. #2 actually was it - I initially made changes in the files at a wrong place. Now I've got my full OpenGL window. Thanks again!

**Comment by lericson** [comment]
Guess I should've checked issues before devising the exact same fix. Oh well!

**Comment by acecilia** [comment]
Is this still an issue?

**Comment by lericson** [comment]
Unless it's been fixed I don't see how it wouldn't still be an issue.

**Comment by acecilia** [comment]
I just installed it from pip, version 0.10.0, which is the last release. I see that is released in 2016. Is there other recommended way of installing pyqtgraph, or other package manager with newer versions?

**Comment by acecilia** [comment]
Seems fixed in https://github.com/pyqtgraph/pyqtgraph/pull/516, but there are several linked issues/PR there and it is not clear if it is 100% fixed

**Comment by eupston** [comment]
Thank you @mshunshin! updated the RawImageWidget.py and GLViewWidget.py with "* self.devicePixelRatio()" and fixed it! 

Many thanks!

**Comment by kassouf** [comment]
OpenGL displays still doesn't work on my MacBook Pro:  Images render in quarter the window.  I fixed by overriding width() and height() in GLViewWidget.  

I added these two functions in class GLViewWidget (GLViewWidget.py).  I use python3 the syntax for 2.x is same same but different.

    def width(self):
        return super().width() * self.devicePixelRatio()

    def height(self):
        return super().height() * self.devicePixelRatio()

I haven't needed to change any of the functions for RawImageWidget.py.   I don't think I use that module.  But if it has the same problem, then this fix will probably work just fine there too.

**Comment by RaphaelMaschinsen** [comment]
I still have the same problem on my MacBook Pro (10.14.5) with python 3.5.6, pyqtgraph version 0.10.0 & PyQt5 version 5.12.2.

**Comment by j9ac9k** [comment]
@RaphaelMaschinsen 

Can you check with the current development version of pyqtgraph?  You can install it by running `pip install git+https://github.com/pyqtgraph/pyqtgraph.git@develop`

**Comment by RaphaelMaschinsen** [comment]
Thanks **j9ac9k**, with the current development version the problem is fixed for me! However if i set the viewport now with: 
```
self.win = gl.GLViewWidget()
self.win.setGeometry(0, 0, 800, 500)
self.win.opts['viewport'] = self.win.getViewport()
self.win.opts['distance'] = 30
```
I get a black window with noting rendered in it (this doesn't actually matter to me since setting the viewport was only part of my hack to display my plots with the correct size).

If i set the viewport with `self.win.opts['viewport'] = (0, 0, 800, 500)` in the snippet from above, it works as expected.

**Comment by j9ac9k** [comment]
@RaphaelMaschinsen thanks for following up.  I'm not certain that's a bug, from the time you `setGeometry` to the time you `getViewport` you may need an event loop to finish running to grab the right values.  I actually am not that familiar with the openGL stuff here in pyqtgraph, but if you can identify where the issue is, or see an existing pull request that addresses this, I'll gladly look it over.

**Comment by j9ac9k** [comment]
Just triggered this issue on windows on a hidpi display, but only when I'm using fractional scaling ... looking at what matplotlib does ( https://github.com/matplotlib/matplotlib/blob/master/lib/matplotlib/backends/backend_qt5.py ), I got something to work _if_ you are using a scaling factor < 2, but if you're using a scaling factor of 2, it doesn't work... anyway going to keep at this for a bit longer
